backend:
  name: github
  repo: savutro/dev-docs
  branch: main
  base_url: "https://docs.savutro.dev"
  auth_type: "token"
  token: ""

search: true
media_folder: "static/img" 
publish_mode: editorial_workflow

define: 
  body: &body
    label: "Content"
    name: "body"
    widget: "markdown"
    required: false

collections:
  - name: "zolaBlog"
    label: "Zola Blog"
    folder: "projects/zolaBlog"
    summary: "{{filename}} - {{fields.title}}"
    create: true
    delete: true
    editor:
      preview: false
    fields:
      - *body